# Generated by Django 4.2.7 on 2026-03-26 15:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('FASTENERS', 'Fasteners'), ('BEARINGS', 'Bearings'), ('SHAFTS', 'Shafts'), ('SHEET_METAL', 'Sheet Metal'), ('MOTORS', 'Motors'), ('ELECTRONICS', 'Electronics'), ('CUSTOM_MACHINED', 'Custom Machined Parts')], max_length=50)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('unit_type', models.CharField(choices=[('NOS', 'Numbers'), ('KG', 'Kilograms'), ('METER', 'Meters')], default='NOS', max_length=20)),
                ('weight_per_unit', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=10, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_changed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('ADDED', 'Stock Added'), ('USED', 'Stock Used')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.component')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('components', models.ManyToManyField(through='inventory.BOMItem', to='inventory.component')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bomitem',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.component'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.project'),
        ),
        migrations.AlterUniqueTogether(
            name='bomitem',
            unique_together={('project', 'component')},
        ),
    ]
